version: "3.3"

networks:
  default:

secrets:
  DB_PASSWORD:
    file: ./secrets/DB_PASSWORD

configs:
  prometheus.yml:
    file: ./configs/prometheus.yml

services:
  m_active:
    image: "monitor_active:2.0.0"
    ports:
      - 9091:9091
    environment:
      DB_HOSTNAME: '192.168.1.100'
      DB_USERNAME: 'rocp'
      DB_DATABASE: 'rocp' 
      POLL_INTERVAL: 720
      PROMETHEUS_PORT: 9091
    secrets:
      - source: DB_PASSWORD
        target: /run/secrets/DB_PASSWORD

  prometheus:
    image: prom/prometheus
    user: "1000:1000"
    ports:
     - 9090:9090
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - ./data/prometheus:/prometheus

  grafana:
    image: grafana/grafana
    user: "1000:1000"
    ports:
     - 3000:3000
    volumes:
     - ./data/grafana:/var/lib/grafana

